### PR TITLE
Update source_url and issues_url in metadata.rb

### PR DESCRIPTION
**Pull request by gopisaba**
Update the right `source_url` and `issues_url` in metadata.rb

### CODE REVIEW

**Comment by Lasering** [comment]
Thanks for the PR. I'm curious what prompted the PR?

**Comment by gopisaba** [comment]
> Thanks for the PR. I'm curious what prompted the PR?

When I click on the "view source" link on the supermarket, it took me to the original cookbook not to this repo. Hope this PR fixes that problem

**Comment by Lasering** [comment]
Very nice catch. That is indeed very annoying. I think the PR didn't solve it. I'm going to release a new version in supermarket to see if it solves it.

**Comment by Lasering** [comment]
That solved it.

**Pull request merged**
